### ISSUE TITLE
OS support

### ISSUE THREAD

**Issue by stephenlacy** [thlorenz/nif#4]
Annoying feature request, support other OSs.
As an idea, instead of checking if the brew package `chrome-cli` is installed, you could match a similar binary check as: https://github.com/hughsk/chrome-location

**Comment by thlorenz** [comment]
Totally would love that. Open to PRs that implement it.
Personally tapped for time ATM.

And BTW not annoying at all, the more flexible this becomes, the better. Please make sure though that things still work with chrome-cli as it is currently, i.e. don't break existing users.

**Comment by marcbachmann** [comment]
Those launch args of the chrome executable would be cross platform compatible:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/tmp/some-unique-id-to-enforce-launch-in-debug-mode --no-first-run --remote-debugging-port=9222 http://localhost:9222/devtools/inspector.html\?experiments\=true\&v8only\=true\&ws\=127.0.0.1:9229/5fff7d4f-7b17-45e0-9f68-9a0ef713421c
```

**Comment by marcbachmann** [comment]
To get the path of the chrome app, we could use `mdfind kind:application 'Google Chrome.app'` on mac.

**Comment by thlorenz** [comment]
Yeah but already working on OSX (just needs a simple `brew install chrome-cli`, but how would it work on Linux and Windows?

Regardless, dedicated Node.js DevTools window landed in Chrome now, so quite honestly I rarely use nif these days.
However if one of you wants to pick this up and propose a PR that'd be great.

Otherwise I'll probably just deprecate this module with a quick doc about the dedicated Node.js Devtool window.

**Comment by marcbachmann** [comment]
I also don't use it anymore. 👋

**Comment by thlorenz** [comment]
OK I'll add that deprecation notice when I get a chance (unless someone else does before me ;) ).
It should have nice screenshots.

**Comment by aleclarson** [comment]
Why is the dedicated DevTools window better than nif?

Can you open it from the terminal?

Does it support multiple inspectors at once? (added in #12)

**Comment by aleclarson** [comment]
I came up with this script:

```sh
TAB_ID=`chrome-cli open 'chrome://inspect/#devices' -n | head -n 1 | awk '{ print $2 }'`
sleep 0.5
chrome-cli execute "document.getElementById('node-frontend').click()" -t $TAB_ID && chrome-cli close -t $TAB_ID
```

Maybe the `nif` script can be replaced with this. ;)

I also posted it on StackOverflow: https://stackoverflow.com/a/49710508/2228559
